### PR TITLE
Don't forget previously discovered characteristics

### PR DESCRIPTION
**Pull request by elafargue**
... when calling discoverCharacteristics multiple times in a program.

Without this fix, we get crashes when unsubscribing, and never receive 'data' events on previously subscribed characteristics if calling discoverCharacteristics multiple times with different uuid lists.

This PR includes comments/feedback from #730

### CODE REVIEW

**Comment by elafargue** [comment]
These are my changes. I will include follow-up commits that roll in the fixes described in the suggestions on #730 once I have tested those.

**Comment by elafargue** [comment]
@jacobrosenthal tested this overnight with multiple connects/disconnects and discoveries, as well as multiple devices connected at the same time, all working fine. This removes a lot of irritating crashes that occur when using noble intensively.

**Comment by jacobrosenthal** [comment]
What about that early exit PR https://github.com/sandeepmistry/noble/pull/383/files , that seemed kind of a classy way to do it. Can you run that and see if it similarly works well?

**Comment by elafargue** [comment]
#383 won't work on its own, because it doesn't address the fact the bindings are squashing the references to previously discovered - and potentially already subscribed - services/characteristics. I can look at adding the early exit pattern of that PR if you want, it should speed things up a little bit. I'll try either way and report.

**Comment by elafargue** [comment]
OK, just checked, with #383 on its own, the code crashes again at it did earlier - that PR might have solved edge cases, but it doesn't seem to provide a complete solution like this PR does.

Let me know if you can try this PR on your side and test on your side, and whether it works for you, merging it would be a tremendous help.

**Comment by elafargue** [comment]
Did a few more tests - multiple connect/disconnect, multiple "discover" for services and characteristics in each session, this PR solves all the crashes or hangs I got earlier whereas the simple fix to "noble.js" in #383 really does not, I'm afraid.

**Comment by sandeepmistry** [comment]
@elafargue thanks for updating, this looks good visually to me.

We'll need to do some testing here before merging.

**Comment by jacobrosenthal** [comment]
Ill take a look with some of my existing code. @monteslu do we need anything for webble?

@tripish @Chondrules does this hit your needs from your previous PR?

**Comment by monteslu** [comment]
I think we're good on the web ble bindings.  The call to `service.getCharacteristics()` seems to cache the characteristics internally in the web bluetooth api.  I've called it manually several times and get the same characteristics back.

**Comment by jacobrosenthal** [comment]
Last attempt to try to ping @tripish @Chondrules to see if this solves their old PRs #383 and #541

**Comment by BrantRoom3327** [comment]
Sorry @jacobrosenthal don't have any time to test your patch.  Gave it a glance and it seems like it could be a fix for the issue I was seeing.  If I get a chance to later I will but don't let me hold up anything.

**Comment by elafargue** [comment]
Thank you!

**Pull request merged**
