### PR TITLE
scanStart does not emit an error parameter

### PR DESCRIPTION
**Pull request by LookingSharp**

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@LookingSharp I've made that change recently, it hasn't been published to npm yet.

See: https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L69

Let me know if I'm missing something else though ...

**Comment by LookingSharp** [comment]
@sandeepmistry that makes sense, but this fix is actually going to make things harder for me.

[Issue 176](https://github.com/sandeepmistry/noble/issues/176) tracks the case where sometimes the adapter comes back unsupported, even though it may have worked on the run before and will work on the next run.  Recent investigation revealed that if I ignore that and start scanning anyway, things still work (though noble.state never recovers from unsupported).  With this fix I won't be able to scan in this case.  Let me know if you get a chance to look at the new info in issue 176.

**Comment by sandeepmistry** [comment]
@LookingSharp I'm confident #176 will be solved before publishing a new version to npm.

**Comment by LookingSharp** [comment]
Awesome, thanks @sandeepmistry

**Pull request closed without merging**
