### PR TITLE
Enable distributed mode on windows

### PR DESCRIPTION
**Pull request by Loghorn**
Windows doesn't yet support all the features noble requires, but nothing prevents using noble "distributed mode" on it.

I fixed a couple of bugs in the distributed and websocket bindings and enabled distributed binding on Windows by default. This allows to create a noble application that runs on Windows and accepts connection from a remote client running on Linux.

You can test it by running the sample "advertisement-discovery.js" on a Windows machine and on a Linux machine start "node ws-slave.js <ip address of win machine>".

This will fix issue #201 and patches temporarily #84 until Windows will have a full BLE API.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@Loghorn thanks for the pull request, I've manually cherry picked https://github.com/Loghorn/noble/commit/44336451b4106e0cbdc33600aedd2f03b1f39f5d and https://github.com/Loghorn/noble/commit/db626602f2bbd21c3cd1ae6c25abb10e5ba6567e

What's the intended use case for this? I'm trying to understand if there is a broad scenario for usage. I'm concerned it will give false hope for noble actually supporting windows, when is doesn't.

cc/ @bragma

**Comment by bragma** [comment]
My use case is to run the application in windows while getting BT data from a remote device, in particular small IoT devices missing a proper debugging environment. I think Visual Studio Code is a great environment for node development, way better than using node debugger on a textual console. With this PR of @Loghorn I can debug in VSC while having ws-slave running on the device.
Please consider the PR.

**Comment by Loghorn** [comment]
@sandeepmistry my use case is similar to @bragma one. I develop for small devices without a display and debugging can be really painful. However, by running my app on windows and connecting it to remote devices using noble facilities already present and working (after the bugfix I made :-) I can leverage all the tools available on windows, like Visual Studio or the new Visual Studio Code.
Also, by enabling distributed mode on windows, you can build a working Bluetooth client that can connect to multiple remote devices or to emulated Bluetooth sensors.
I know that this does not mean that noble is fully working on windows, but this can be made clear in the documentation and/or by emitting a warning when the library is loaded on windows.

**Comment by sandeepmistry** [comment]
@bragma @Loghorn thanks for the explanation on your use case.

I'm going to hold off merging this until there is more demand. I anticipate this being a support nightmare ... so the pros out way the cons for me now.

**Comment by Loghorn** [comment]
@sandeepmistry I understand your concerns.
Thank you anyway for considering this PR.

**Comment by sandeepmistry** [comment]
@Loghorn thanks for understanding and the patches to fix up distributed/web socket mode!

Closing this for now ...

**Pull request closed without merging**
