### PR TITLE
Don't forget previously discovered characteristics

### PR DESCRIPTION
**Pull request by elafargue**
... when calling discoverCharacteristics multiple times in a program.

Without this fix, we get crashes when unsubscribing, and never receive 'data' events on previously subscribed characteristics if calling discoverCharacteristics multiple times with different uuid lists.

### CODE REVIEW

**Comment by elafargue** [comment]
High Sierra patches for included there automatically, sorry

**Comment by elafargue** [comment]
@sandeepmistry  -> Can you consider merging this one? Will solve the conflicts w/ your latest PR merge ASAP.

**Comment by jacobrosenthal** [comment]
Clean it up, well consider it.

**Comment by elafargue** [comment]
@jacobrosenthal should be fine now - let me know

**Comment by jacobrosenthal** [comment]
Lets get brackets around if statements and be rebased on master, and squash while you're at it.

**Comment by jacobrosenthal** [comment]
Also it seems like theres maybe some more functionality in #541 what do you like in there to bring in?

**Comment by jacobrosenthal** [comment]
Also, what about early exit like this?
https://github.com/sandeepmistry/noble/pull/383/files

**Comment by elafargue** [comment]
OK, I'll restart a new separate branch based on all your input and submit a new PR - on this one there are mixes between my changes and the High Sierra patches, so a new clean PR that includes what's relevant from #541 and #383 is probably a better solution.

**Comment by elafargue** [comment]
Opening new clean PR

**Pull request closed without merging**
